agh_commands.c: fixes
agh_cmd_op_answer_error: add missing initialization of retval to 0, and check for more conditions so we can ignore return values for the functions we invoke.
Furthermore, do not leak memory on failure when dup == FALSE.

agh_cmd_op_match: allocate our answer earlier, so agh_cmd_op_answer_error can use it